name: "Shell Commands"

on: [pull_request]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo Hello World
        run: echo "Hello World"
      - name: Multiline shell commands
        run: |
          node -v
          npm -v
          yarn -v
